AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToMany:
        criterias:
            targetEntity: AppBundle\Entity\Criteria
            inversedBy: users

        places:
            targetEntity: AppBundle\Entity\Place
            mappedBy: users

    oneToMany:
        participations:
            targetEntity: AppBundle\Entity\Participation
            mappedBy: user
